#!/bin/bash

cmd="./pipe "
iter=0

while [[ $# -gt 1 ]]; do
  key="$1"

  case $key in
    --blade|-s1.1|-v|-vv)
      cmd="${cmd}$1 "
      shift;;
    --model|--weights|--speculator|-t|-o)
      cmd="${cmd}$1 $2 "
      shift
      shift;;
    -avg)
      iter=$2
      shift
      shift;;
  esac

done

file=$1

if [[ iter -gt 0 ]]; then 
  for i in $(seq 1 $iter); do 
    bash -c "$cmd$file" | tail -n1
  done | awk '{sum += $2} END {print "avg of", NR, ":", sum/NR}'
else 
  bash -c "$cmd$file" | tail -n1
fi
