#!/bin/bash

weight=simple
while [[ $# -gt 1 ]]; do
  key="$1"

  case $key in
    -w)
      weight=$2
      shift
      shift;;
  esac

done

ntest=$1
iters=20
dump="dump/test${ntest}.dump"
: '
rm -f "${dump}"
make pipe
make run_blade

echo
echo "=== running test${ntest}nb"
echo "ast:" >> "${dump}"
echo >> "${dump}"
cat "test/test${ntest}.txt" >> "${dump}"
printf "\ndefault speculator:\n" >> "${dump}"
printf "uniform: " >> "${dump}"; ./piperun --model uniform "test/test${ntest}.txt" >> "${dump}"
printf "fence: " >> "${dump}"; ./piperun --model fence "test/test${ntest}.txt" >> "${dump}"
printf "fence2: " >> "${dump}"; ./piperun --model fence2 "test/test${ntest}.txt" >> "${dump}"
printf "simple: " >> "${dump}"; ./piperun --model simple "test/test${ntest}.txt" >> "${dump}"
printf "\nout of order speculator:\n" >> "${dump}"
printf "uniform: " >> "${dump}"; ./piperun --model uniform --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "fence: " >> "${dump}"; ./piperun --model fence --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "fence2: " >> "${dump}"; ./piperun --model fence2 --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "simple: " >> "${dump}"; ./piperun --model simple --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
echo "=== test${ntest}nb ended"

echo
echo "=== running test${ntest}b1"
echo >> "${dump}"
./run_blade "test/test${ntest}.txt" >> "${dump}"
printf "\ndefault speculator:\n" >> "${dump}"
printf "uniform: " >> "${dump}"; ./piperun --blade --model uniform "test/test${ntest}.txt" >> "${dump}"
printf "fence: " >> "${dump}"; ./piperun --blade --model fence "test/test${ntest}.txt" >> "${dump}"
printf "fence2: " >> "${dump}"; ./piperun --blade --model fence2 "test/test${ntest}.txt" >> "${dump}"
printf "simple: " >> "${dump}"; ./piperun --blade --model simple "test/test${ntest}.txt" >> "${dump}"
printf "\nout of order speculator:\n" >> "${dump}"
printf "uniform: " >> "${dump}"; ./piperun --blade --model uniform --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "fence: " >> "${dump}"; ./piperun --blade --model fence --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "fence2: " >> "${dump}"; ./piperun --blade --model fence2 --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "simple: " >> "${dump}"; ./piperun --blade --model simple --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
echo "=== test${ntest}b1 ended"
'
echo
echo "=== running test${ntest}b2"
echo >> "${dump}"
./run_blade --weights ${weight} "test/test${ntest}.txt" >> "${dump}"
printf "\ndefault speculator:\n" >> "${dump}"
printf "uniform: " >> "${dump}"; ./piperun --blade --weights ${weight} --model uniform "test/test${ntest}.txt" >> "${dump}"
printf "fence: " >> "${dump}"; ./piperun --blade --weights ${weight} --model fence "test/test${ntest}.txt" >> "${dump}"
printf "fence2: " >> "${dump}"; ./piperun --blade --weights ${weight} --model fence2 "test/test${ntest}.txt" >> "${dump}"
printf "simple: " >> "${dump}"; ./piperun --blade --weights ${weight} --model simple "test/test${ntest}.txt" >> "${dump}"
printf "\nout of order speculator:\n" >> "${dump}"
printf "uniform: " >> "${dump}"; ./piperun --blade --weights ${weight} --model uniform --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "fence: " >> "${dump}"; ./piperun --blade --weights ${weight} --model fence --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "fence2: " >> "${dump}"; ./piperun --blade --weights ${weight} --model fence2 --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
printf "simple: " >> "${dump}"; ./piperun --blade --weights ${weight} --model simple --speculator outoforder -avg ${iters} "test/test${ntest}.txt" >> "${dump}"
echo "=== test${ntest}b2 ended"


